apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
  labels:  
    app: dev-pod
    env: dev
spec:
  containers:
    - name: startup-container 
      image: busybox   
      ports:
        - containerPort: 80
          protocol: TCP
      startupProbe:
        httpGet:
          path: ./rajashekar
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3

            
